"""Correcion tabla productos

Revision ID: 01bc711b92e5
Revises: 479bcfed5796
Create Date: 2026-04-10 16:09:31.340811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bc711b92e5'
down_revision = '479bcfed5796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###
