"""correcciones finales

Revision ID: 036e1ef6a07f
Revises: 01bc711b92e5
Create Date: 2026-04-17 20:54:40.049850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036e1ef6a07f'
down_revision = '01bc711b92e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    with op.batch_alter_table('movimientos_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('movimientos_stock', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
