"""Agregacion de proveedores

Revision ID: d305dfd9a694
Revises: 9abfbde50bec
Create Date: 2026-04-09 22:35:19.981509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd305dfd9a694'
down_revision = '9abfbde50bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roveedores',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roveedores')
    # ### end Alembic commands ###
